### ISSUE TITLE
plb.col or pl.col

### ISSUE THREAD

**Issue by deanm0000** [pola-rs/polars-xdt#29]
What's the difference between `plb.col` and `pl.col`?

I did the example from the readme with just pl.col and it worked the same. The `class BColumn is almost the same as polars class Column except for the 

```
    @property
    def bdt(self) -> ExprBusinessDateTimeNamespace:
        ...
```
Is the intention that the bdt namespace only works on `plb.col`s?

**Comment by MarcoGorelli** [comment]
there's no difference, `plb` is just to trick type checkers if you're relying on them for autocomplete

**Comment by MarcoGorelli** [comment]
closing for now, not really sure what to do about type checkers here
