### ISSUE TITLE
Use holidays crate

### ISSUE THREAD

**Issue by ion-elgreco** [pola-rs/polars-xdt#53]
We can use the holidays crate https://docs.rs/holidays/latest/holidays/index.html in the areas where we can pass holidays

**Comment by ion-elgreco** [comment]
Here is a working version of it: https://github.com/ion-elgreco/polars-xdt/blob/feat/holidays_range/src/holiday.rs

Sadly, it's only limited to years falling between 2000 and 2030

**Comment by MarcoGorelli** [comment]
thanks! might be better to  let users pass in their own holidays then?

**Comment by ion-elgreco** [comment]
Likely better, you get 100x speed ups though with the xdt.holiday_range :P
