### ISSUE TITLE
offset_by panicking in polars 0.20.23

### ISSUE THREAD

**Issue by alkment** [pola-rs/polars-xdt#75]
The current version (0.14.12) of polars-xdt seems to be incompatible with polars==0.20.23

The following snippet can be used to replicate the error.

` pl.DataFrame({'d':[datetime.date.today(),datetime.date.today()]}).with_columns(pl.col('d').xdt.offset_by('1bd'))`

This raises a `PanicException: not implemented`

Tested on Linux.

**Comment by MarcoGorelli** [comment]
thanks for the report, I just noticed this in another plugin - taking a look

note that Polars now has `add_business_days`, so you can use that directly

**Comment by MarcoGorelli** [comment]
this should now be fixed in recent Polars versions, closing then
